apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ai_edge_1.yaml
  - ai_edge_2.yaml
  - ai_edge_3.yaml
  - 20-vm-linux.yaml
  - hello-ecs.yaml

patches:
  - patch: |
      - op: replace
        path: /spec/className
        value: best-effort-xsmall
    target:
      kind: VirtualMachine
      name: linux-vm
