apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - web-server.yaml
  - esx-ntp-config.yaml
  - ai_edge_1.yaml
  - ai_edge_2.yaml
  - ai_edge_3.yaml
  - k8s-dashboard.yaml

patches:
  - patch: |
      - op: replace
        path: /spec/className
        value: best-effort-xsmall
    target:
      kind: VirtualMachine
      name: linux-vm
